apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-chart.fullname" . }}-java
  namespace : {{ .Values.namespace}}
  labels:
    app: java
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java
